//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources
{
    using System;


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages()
        {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Album with name {0} already exist.
        /// </summary>
        public static string AlbumAlreadyExist
        {
            get
            {
                return ResourceManager.GetString("AlbumAlreadyExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Album with Id {0} doesn&apos;t exist.
        /// </summary>
        public static string AlbumNotFound
        {
            get
            {
                return ResourceManager.GetString("AlbumNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Playlist with name {0} already exist.
        /// </summary>
        public static string PlaylistAlreadyExist
        {
            get
            {
                return ResourceManager.GetString("PlaylistAlreadyExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Playlist with ID {0} doesn&apos;t exist.
        /// </summary>
        public static string PlaylistNotFound
        {
            get
            {
                return ResourceManager.GetString("PlaylistNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Track with name {0} already exist.
        /// </summary>
        public static string TrackAlreadyExist
        {
            get
            {
                return ResourceManager.GetString("TrackAlreadyExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Track with ID {0} already in playlist with ID {1}.
        /// </summary>
        public static string TrackAlreadyInPlaylist
        {
            get
            {
                return ResourceManager.GetString("TrackAlreadyInPlaylist", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Track with ID {0} doesn&apos;t exist.
        /// </summary>
        public static string TrackNotFound
        {
            get
            {
                return ResourceManager.GetString("TrackNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Track with ID {0} doesn&apos;t exist in playlist with ID {1}.
        /// </summary>
        public static string TrackNotInPlaylist
        {
            get
            {
                return ResourceManager.GetString("TrackNotInPlaylist", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на User with ID {0} doesn&apos;t exist.
        /// </summary>
        public static string UserNotFound
        {
            get
            {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}